services:
  accounts:
    image: "accounts-ms:1.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 800M
    networks:
      - backend
  loans:
    image: "loans-ms:1.0"
    container_name: loans-ms
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - backend
# add postgres service
  postgres:
    image: "postgres:14"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "lol"
      POSTGRES_USER: "postgres"
    networks:
      - backend

networks:
  backend:
    driver: bridge